# Generated by Django 3.2.5 on 2021-07-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('ubicacionID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
